### PR TITLE
arXiv Paper 2020

### PR DESCRIPTION
**Pull request by raiben**
**Important**: Work in progress

PDFs generated:
- 2020/02/02: [tropescraper_arxiv.pdf](https://github.com/raiben/made_recommender/files/4144857/tropescraper_arxiv.pdf)

### CODE REVIEW

**Comment by JJ** [comment]
Chart captions should be more descriptive, even if they are going to be described later.

**Comment by JJ** [comment]
OK; I downloaded the old version. Got the new one now.

**Comment by JJ** [comment]
* recent -> easily updated
* The introduction should be more narrative, less terse.
* Please spell check (fulfil -> fulfill)
* You should repeat the questions you make in the introduction in every one of the sections. For instance, section 2 would be "How much has it grown?"
* Nothing is "according to Figure x". It's according to data, shown in Figure x (BTW, it's missing in the PDF)
* Figure should be in capitals always.
* higher average, not bigger average

**Comment by JJ** [comment]
* Add references, at least our already published paper and the DBTropes paper. Also our other technical reports with similar datasets, like StarTroper

**Comment by JJ** [comment]
Why are there two versions of the file, arxiv and arxiv_extended?

**Comment by raiben** [comment]
Hi @JJ ,

Thank you for your comments, I will update the text according to your suggestions and answer the questions.

In the meantime, I have improved the scraper and now the numbers are more accurate and the matrix is double the dense it was before (from an average of 40 tropes per film to an average of 104). Whilst the texts are not changed yet, the numbers are, so if you want to take a look feel free 😀 . I have uploaded the file to this comment:
[tropescraper_arxiv.pdf](https://github.com/raiben/made_recommender/files/4486897/tropescraper_arxiv.pdf)

Some interesting things to look at:
- The graph "Number of tropes by film" has a funny wave... I don't really know how to explain it, I have to take a deeper look.
- There are a lot of common films in the top 50, that kinda makes sense.
- There are not many common tropes in the top 50. I am trying to analyze it but it looks that TV Tropes changed a lot, and tropes are evolving... some are not used anymore... but I really have to study case by case. So far, no more differences due missing scrapping.

Best!

**Pull request merged**
